<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'page#indexJob', 'url' => '/jobs/{jobId}', 'verb' => 'GET'],
		['name' => 'health#index', 'url' => '/api/v1/health', 'verb' => 'GET'],
		['name' => 'job#index', 'url' => '/api/v1/jobs', 'verb' => 'GET'],
		['name' => 'job#create', 'url' => '/api/v1/jobs', 'verb' => 'POST'],
		['name' => 'job#show', 'url' => '/api/v1/jobs/{jobId}', 'verb' => 'GET'],
		['name' => 'job#update', 'url' => '/api/v1/jobs/{jobId}', 'verb' => 'PUT'],
		['name' => 'job#delete', 'url' => '/api/v1/jobs/{jobId}', 'verb' => 'DELETE'],
		['name' => 'job#duplicate', 'url' => '/api/v1/jobs/{jobId}/duplicate', 'verb' => 'POST'],
		['name' => 'job#discard', 'url' => '/api/v1/jobs/{jobId}/discard', 'verb' => 'POST'],
		['name' => 'job#pause', 'url' => '/api/v1/jobs/{jobId}/pause', 'verb' => 'POST'],
		['name' => 'job#resume', 'url' => '/api/v1/jobs/{jobId}/resume', 'verb' => 'POST'],
		['name' => 'job#markReady', 'url' => '/api/v1/jobs/{jobId}/ready', 'verb' => 'POST'],
		['name' => 'job#worklistPreview', 'url' => '/api/v1/jobs/{jobId}/worklist-preview', 'verb' => 'GET'],
		['name' => 'job#queueExecution', 'url' => '/api/v1/jobs/{jobId}/queue-execution', 'verb' => 'POST'],
		['name' => 'job#processNow', 'url' => '/api/v1/jobs/{jobId}/process-now', 'verb' => 'POST'],
		['name' => 'sort#state', 'url' => '/api/v1/jobs/{jobId}/sort-state', 'verb' => 'GET'],
		['name' => 'sort#assign', 'url' => '/api/v1/jobs/{jobId}/assign', 'verb' => 'POST'],
		['name' => 'sort#skip', 'url' => '/api/v1/jobs/{jobId}/skip', 'verb' => 'POST'],
		['name' => 'sort#undo', 'url' => '/api/v1/jobs/{jobId}/undo', 'verb' => 'POST'],
		['name' => 'sort#removeQueueItem', 'url' => '/api/v1/jobs/{jobId}/queue/{queueItemId}', 'verb' => 'DELETE'],
		['name' => 'sort#position', 'url' => '/api/v1/jobs/{jobId}/position', 'verb' => 'POST'],
		['name' => 'target#index', 'url' => '/api/v1/targets', 'verb' => 'GET'],
		['name' => 'target#create', 'url' => '/api/v1/targets', 'verb' => 'POST'],
		['name' => 'favorite#index', 'url' => '/api/v1/favorites', 'verb' => 'GET'],
		['name' => 'favorite#create', 'url' => '/api/v1/favorites', 'verb' => 'POST'],
		['name' => 'favorite#reorder', 'url' => '/api/v1/favorites/reorder', 'verb' => 'POST'],
		['name' => 'favorite#delete', 'url' => '/api/v1/favorites/{favoriteId}', 'verb' => 'DELETE'],
		['name' => 'folder#index', 'url' => '/api/v1/folders', 'verb' => 'GET'],
		['name' => 'log#index', 'url' => '/api/v1/logs', 'verb' => 'GET'],
		['name' => 'settings#index', 'url' => '/api/v1/admin/settings', 'verb' => 'GET'],
		['name' => 'settings#update', 'url' => '/api/v1/admin/settings', 'verb' => 'PUT'],
		['name' => 'support#export', 'url' => '/api/v1/support/export', 'verb' => 'GET'],
	],
];
